server {
    listen 81 default_server;
    listen [::]:81 default_server;

    root /var/www/html;

    index index.php;

    server_name _;

    # location / {
    #     # First attempt to serve request as file, then
    #     # as directory, then fall back to displaying a 404.
    #     try_files $uri $uri/ =404;
    # }

    # location ~ \.php$ {
    location / {
        include fastcgi_params;
        fastcgi_pass adminer:9000;
        fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        # Return a 404 error if PHP-FPM returns "File not found"
        fastcgi_intercept_errors on;
        error_page 404 =404 /404.html;
    }
}
