FROM debian:bullseye

RUN apt-get update -y && \
    apt-get -y install vim net-tools \
    wget \
	curl \
	bash \
	php \
	php-cgi \
	php-mysql \
	php-fpm \
	php-pdo \
	php-gd php-cli \
	php-mbstring \
	redis \
	php-redis 

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

COPY ./tools/wordpress.sh /home

WORKDIR /var/www/html/

# I need to install wp_cli command and put it in the right directory /usr/local/bin
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
  && chmod +x wp-cli.phar \
  && mv wp-cli.phar /usr/local/bin/wp

#Create the folder to enable php start
RUN mkdir -p /run/php

RUN chmod +x /home/wordpress.sh

EXPOSE 9000

ENTRYPOINT [ "/home/wordpress.sh"]

# ENTRYPOINT ["/usr/sbin/php-fpm7.4", "-F"]

CMD ["/usr/sbin/php-fpm7.4", "-F"]